---
apiVersion: v1
kind: Namespace
metadata:
  name: whisper-neuron
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: model-storage-class
  namespace: whisper-neuron
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  iops: "16000"
  throughput: "1000"
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-claim
  namespace: whisper-neuron
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: model-storage-class
  resources:
    requests:
      storage: 1000Gi 