apiVersion: batch/v1
kind: Job
metadata:
  name: whisper-model-compile
  namespace: whisper-neuron
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: whisper-compile
    spec:
      restartPolicy: Never
      tolerations:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
      - name: model-compiler
        image: public.ecr.aws/v2f5y6u4/whisper-neuron/compile:latest@sha256:9f07c6ae98ed6fa6616811cf359153b2472996603abc6cf9d8ee84522b65a36a
        imagePullPolicy: Always
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
        resources:
          requests:
            aws.amazon.com/neuron: "1"
            memory: "30G"
            cpu: "30"
          limits:
            aws.amazon.com/neuron: "1"
            memory: "128Gi"
            cpu: "32"
        volumeMounts:
        - name: model-storage
          mountPath: /models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-claim
