apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::849244120529:role/VSCodeServer-Summit-VSCodeInstanceBootstrapRole-fGpd35mzoZc8
      username: admin
      groups:
        - system:masters
