apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-inference-deployment
  namespace: whisper-neuron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-inference
  template:
    metadata:
      labels:
        app: whisper-inference
    spec:
      tolerations:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
      - name: whisper-inference
        image: public.ecr.aws/v2f5y6u4/whisper-neuron/service:latest@sha256:b19d28bca1bbeb12b85665408381e2c5df08160247abe26c0b800f4ee7f32bfd
        imagePullPolicy: Always
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
        resources:
          requests:
            aws.amazon.com/neuron: "1"
            memory: "30G"
            cpu: "30"
          limits:
            aws.amazon.com/neuron: "1"
            memory: "128Gi"
            cpu: "32"
        env:
        - name: MODEL_PATH
          value: "/models"
        - name: PORT
          value: "8000"
        - name: NEURON_RT_NUM_CORES
          value: "1"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-storage
          mountPath: /models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-claim
---
# Service to access the Whisper deployment 
apiVersion: v1
kind: Service
metadata:
  name: whisper-inference-service
  namespace: whisper-neuron
spec:
  selector:
    app: whisper-inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
